services:
  outbox-cdc-postgres:
    container_name: outbox_cdc_postgres
    build:
      context: .
      dockerfile: Dockerfile.pg
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpw
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - "./infrastructure/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro,z"
      - "./infrastructure/postgres/init-db:/docker-entrypoint-initdb.d:ro,z"
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
  outbox-cdc-kafka:
    container_name: outbox_cdc_kafka
    image: docker.io/apache/kafka:4.1.1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://outbox-cdc-kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
  outbox-cdc-kafka-connect-standalone:
    container_name: outbox_cdc_kafka_connect_standalone
    image: docker.io/apache/kafka:4.1.1
    depends_on: [outbox-cdc-postgres, outbox-cdc-kafka]
    ports:
      - "8083:8083"
    volumes:
      - "./infrastructure/kafka-connect/config/connect-standalone.properties:/opt/kafka/connect/config/connect-standlone.properties:rw,z"
      - "./infrastructure/kafka-connect/plugins:/opt/kafka/connect/plugins:rw,z"
      - "./infrastructure/kafka-connect/debezium/outbox-postgres-connector.json:/opt/kafka/connect/debezium/outbox-postgres-connector.json:rw,z"
    command:
      [
        /opt/kafka/bin/connect-standalone.sh,
        /opt/kafka/connect/config/connect-standlone.properties,
        /opt/kafka/connect/debezium/outbox-postgres-connector.json,
      ]
  outbox-cdc-kafka-consumer:
    container_name: outbox_cdc_kafka_consumer
    image: docker.io/apache/kafka:4.1.1
    depends_on: [outbox-cdc-kafka]
    command:
      [
        /opt/kafka/bin/kafka-console-consumer.sh,
        --bootstrap-server=outbox-cdc-kafka:9092,
        --from-beginning,
        --topic=order.events,
        --property,
        print.headers=true,
      ]
